en:
  activemodel:
    errors:
      models:
        validated_object:
          attributes:
            name:
              already_exists: "Name already exists"
